version: "3.9"
services:
  debug:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - metrics-gateway
    environment:
      WAIT_HOSTS: 'metrics-gateway:9091'

  metrics-gateway:
    image: prom/pushgateway:v1.4.2
